### ISSUE TITLE
AL:GO! fails with System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0

### ISSUE THREAD

**Issue by sbuescher** [Microsoft/nav-arm-templates#44]
After going directly to vs code on the VM the command AL:GO fails with:

System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0...

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) ---> System.IO.FileLoadException: Could not load file or assembly 'Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   --- End of inner exception stack trace ---
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.MessageWriter..ctor(Stream outputStream, IMessageSerializer messageSerializer)
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.StdioServerChannel.Initialize(IMessageSerializer messageSerializer) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\StdioServerChannel.cs:line 27
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.Channel.ChannelBase.Start(MessageProtocolType messageProtocolType, ProtocolEndpointCompletionSource completionSource) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\Channel\ChannelBase.cs:line 40
   at Microsoft.Dynamics.Nav.EditorServices.Protocol.MessageProtocol.ProtocolEndpoint.<Start>d__4.MoveNext() in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Protocol\MessageProtocol\ProtocolEndpoint.cs:line 27
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Prod.EditorServices.Host.Program.Main(String[] args) in C:\Agent\_work\47\s\source\Prod\Microsoft.Dynamics.Nav.EditorServices.Host\Program.cs:line 103
[Error - 8:44:21 AM] Connection to server got closed. Server will not be restarted.

Any idea?

Kind regards,
Sebastian

**Comment by freddydk** [comment]
You don't state which version you are deploying, so I can only guess that you are running into the issue, Erik is describing here: https://dynamicsuser.net/nav/b/admin/posts/al-crash-with-dynamics-nav-2018-cu5-109454445#.Wv8-cD1OnVQ.twitter

**Comment by sbuescher** [comment]
Hi Freddy,

thanks!

Best,
Sebastian
